<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cb_wishlist"
 *
 * Auto generated by Extension Builder 2013-09-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Wishlist',
	'description' => 'Creates a wishlist for your wishes. Use this extension to organize your giftlist for your event e.g. your wedding, your birthday, etc.',
	'category' => 'plugin',
	'author' => 'Christian Geser',
	'author_email' => 'wishlist-typo3@gmx.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.8.2',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
